name: ci
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  test:
    name: ci ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64

    steps:
      - run: echo "Fake success!"
